name: E2E on Vercel Preview

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Wartet auf das von der Vercel GitHub App erzeugte Preview-Deployment
      # und liefert die Preview-URL als Output (z. B. https://<hash>-<project>.vercel.app)
      - name: Wait for Vercel Preview
        id: vercel
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600

      - name: Show preview URL
        run: echo "Preview URL = ${{ steps.vercel.outputs.url }}"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci || npm i

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Setzt BASE_URL auf die Vercel-Preview, damit der Analytics-Test
      # und alle E2E-Tests gegen die echte Preview laufen.
      - name: Run Playwright tests (against Vercel preview)
        env:
          BASE_URL: ${{ steps.vercel.outputs.url }}
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
          retention-days: 7
