name: Smoke on Vercel Production

on:
  deployment_status:
    types: [success]

permissions:
  contents: read
  deployments: read
  statuses: write

jobs:
  smoke:
    name: smoke
    if: >-
      ${{ github.event.deployment.environment && contains(github.event.deployment.environment, 'Production') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Extract Production URL
        id: url
        run: |
          env_url="${{ github.event.deployment_status.environment_url }}"
          target_url="${{ github.event.deployment_status.target_url }}"
          final_url="$env_url"
          if [ -z "$final_url" ]; then
            final_url="$target_url"
          fi
          if [ -z "$final_url" ]; then
            echo "No environment URL found on deployment_status event" >&2
            exit 1
          fi
          echo "production_url=$final_url" >> "$GITHUB_OUTPUT"

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright smoke tests against Vercel Production
        env:
          BASE_URL: ${{ steps.url.outputs.production_url }}
        run: npx playwright test tests/smoke.spec.ts --reporter=github,html

      - name: Upload Playwright artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts-production
          path: |
            playwright-report
            test-results
          retention-days: 7
